### ISSUE TITLE
memorization v2.0.2

### ISSUE THREAD

**Issue by kazuma11121125** [HSS-Project/HSS-bot#30]
- [x] gnere移動バグ　エラー修正&移動したあとに繰り返して動かすとエラーになる
- [ ] 選択肢自動追加モードバグ修正 答えと同じ選択肢が入り込む
- [ ] memorization_addで予期せぬ動作が起きた場合にsharecodeがFalseになる問題。
- [x] 問題完全削除がバグで動かない
- [ ] 例外処理の追加
- [x] 選択肢追加したあとにeditにする
- [ ] 重複問題が追加された場合、select_titleがエラーを吐く問題の解決(listの中身のtitleが同じになるため)
- [x] 間違った問題数が多いと動くbuttonが動いていない
- [x] select-titleバグ修正

**Comment by kazuma11121125** [comment]
gnere移動バグ
`11月 28 00:55:41 deskmini-kazuma python3[4400]: Traceback (most recent call last):
11月 28 00:55:41 deskmini-kazuma python3[4400]:   File "/home/kazuma1112/.local/lib/python3.10/site-packages/discord/ui/view.py", line 427, in _scheduled_task
11月 28 00:55:41 deskmini-kazuma python3[4400]:     await item.callback(interaction)
11月 28 00:55:41 deskmini-kazuma python3[4400]:   File "/home/kazuma1112/HSS-bot/memorization_discord/select_title.py", line 25, in callback
11月 28 00:55:41 deskmini-kazuma python3[4400]:     await genre.move_genre(str(interaction.user.id),self.genres[int(self.values[0])],sharecode)
11月 28 00:55:41 deskmini-kazuma python3[4400]:   File "/home/kazuma1112/HSS-bot/memorization_maker/genre.py", line 70, in move_genre
11月 28 00:55:41 deskmini-kazuma python3[4400]:     self.user_data["genre"][num_id][before_genre]["sharecodes"].remove(_sharecode)
11月 28 00:55:41 deskmini-kazuma python3[4400]: ValueError: list.remove(x): x not in list
`

**Comment by kazuma11121125** [comment]
`11月 28 01:20:07 deskmini-kazuma python3[11647]: Traceback (most recent call last):
11月 28 01:20:07 deskmini-kazuma python3[11647]:   File "/home/kazuma1112/.local/lib/python3.10/site-packages/discord/ui/view.py", line 427, in _scheduled_task
11月 28 01:20:07 deskmini-kazuma python3[11647]:     await item.callback(interaction)
11月 28 01:20:07 deskmini-kazuma python3[11647]:   File "/home/kazuma1112/HSS-bot/memorization_discord/select_title.py", line 50, in callback
11月 28 01:20:07 deskmini-kazuma python3[11647]:     await SelectTitleResponse(interaction,self.values[0],self.modes).select_response()
11月 28 01:20:07 deskmini-kazuma python3[11647]:   File "/home/kazuma1112/HSS-bot/memorization_discord/select_title.py", line 148, in select_response
11月 28 01:20:07 deskmini-kazuma python3[11647]:     if not await self.ower.owner_check(str(self.intraction.user.id),sharecode):return await self.intraction.response.edit_message(content="403 権限不足で >
11月 28 01:20:07 deskmini-kazuma python3[11647]:   File "/home/kazuma1112/HSS-bot/memorization_maker/owner_manager.py", line 14, in owner_check
11月 28 01:20:07 deskmini-kazuma python3[11647]:     if num_id in self.base_data["memorization"][sharecode]["onwer"]:
11月 28 01:20:07 deskmini-kazuma python3[11647]: KeyError: False
`
問題削除
